レビュー修正＆テーマ切り替え等の実装
NByamane/calculator-app-main pull request #1
Opened 2024-05-29 01:26 UTC by NByamane

以下修正＆追加しました。

- レビューしていただいた部分の修正
- テーマ切り替えボタンの実装
- 画面に入りきらない桁になる場合の実装
　→14桁以上になる数字を押そうとした場合、13桁までしか数値buttonが効かないようにしました
　→計算の都合で14桁以上になる場合、13桁まで表示し、以下を切り捨てエラーのEを追加しました

以下、うまく実装できずに未だ困ってる部分です😇アドバイスいただけますと幸いです🙇‍♀️
・入力中及び結果表示の際に、1000の位ごとにカンマを追加する

2024-05-29 10:45 UTC, NBmaeda requested changes
対応お疲れ様です！
だいぶ完成まで近づいてきたと思うので、改めてコードの中身の部分を見直してみて欲しいと思います。
なので少し細かい部分まで書いていますが、頑張ってチャレンジしてみてください！💪

> ・入力中及び結果表示の際に、1000の位ごとにカンマを追加する

これに関しては、以下の関数を使うと良いかもです💡
ただ使う場合、桁数はみ出ちゃうかもなので再度調整が必要かもしれません。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

2024-05-29 10:45 UTC, NBmaeda commented on src/css/App.css
> +}
レビューの時にReact Developer Tools使いたいので、この指定は解除しておいてください。

2024-05-29 10:45 UTC, NBmaeda commented on src/Components/Calculator.tsx
> +			<ThemeChange onThemeChange={onThemeChange} />
ここの部分はcalculatorの`state`とは無関係だと思うのですが、`Calculator`コンポーネント内でimportされているので、`state`の更新毎にリレンダリングされてしまっています。
なので、`Calculator`コンポーネントから出した方がいいと思います💡

2024-05-29 10:45 UTC, NBmaeda commented on src/Components/ThemeChange.tsx
> +						<button className={`theme1-num ${selectedTheme === 1 ? 'active' : ''}`} onClick={handleThemeChange(1)}>1</button>
ここの`onClick`の型はVSCodeでホバーしたら現れる通り。`React.MouseEventHandler<HTMLButtonElement>`になっています。
なので、`(event: React.MouseEvent<HTMLButtonElement>) => void`の型の関数を渡してあげる必要があります。

また`handleThemeChange(1)`のような渡し方をすると即時関数が実行されてしまうので、好ましくないです。(`handleThemeChange`の中に`console.log()`とか入れてもらうとわかると思います。)
なので、前述の`handleThemeChange`のとこのコメントでも書いたような関数を渡してあげる方が良いです。

2024-05-29 10:45 UTC, NBmaeda commented on src/Components/ThemeChange.tsx
> +		return () => {
ここは後述の`button`要素のところでも書いていますが、`(event: React.MouseEvent<HTMLButtonElement>) => void`型の関数にしてあげる必要があります。
また`handleThemeChange`という関数名も好ましくはなく、`handle`するのはDOMのイベントにしてあげた方がわかりやすいです。

なので、以下のような関数名と関数の中身の方が良いと思っています。
```
const handleClickThemeBtn = (e: React.MouseEvent<HTMLButtonElement>) => {
    // e.target.value をエラーなく使うための型ガード
    if (!(e.target instanceof HTMLButtonElement)) {
      return;
    }
    setSelectedTheme(Number(e.target.value));
    onThemeChange(Number(e.target.value));
  };
```

`ButtonPanel.tsx`の`buttonHandler`関数も併せて見直してみてください！

2024-05-29 10:45 UTC, NBmaeda commented on src/logic/calculate.ts
> +function updateCurrent(buttonValue: string, state: State): State {
ここの関数名を`updateCurrent`にするのであれば、他の`state.current`を更新する処理もまとめてあげた方が良いです💡

2024-05-29 10:45 UTC, NBmaeda commented on src/logic/calculate.ts
> +function handleOperationButton(buttonValue: string, state: State): State {
これ以降の`handle~`も`handleNumberButton`と同じく、関数名と関数内の処理を見直してみてください。

2024-05-30 05:43 UTC, NByamane commented on src/Components/ThemeChange.tsx
> +						<button className={`theme1-num ${selectedTheme === 1 ? 'active' : ''}`} onClick={handleThemeChange(1)}>1</button>
@NBmaeda 
レビューありがとうございます🙇‍♀️
1点質問させてください🙏

>またhandleThemeChange(1)のような渡し方をすると即時関数が実行されてしまうので、好ましくないです。(handleThemeChangeの中にconsole.log()とか入れてもらうとわかると思います。)
>なので、前述のhandleThemeChangeのとこのコメントでも書いたような関数を渡してあげる方が良いです。

こちらなのですが、`onClick={() => handleThemeChange(1)}`といった書き方をするという意味でしょうか？🤔

以前、FE課題を行った際にイベントハンドラーに直接アロー関数を渡すことにはレンダリングの観点から注意が必要であるとの教えをいただいたかと思うのですが、今回の場合は前回の書籍検索のように、親コンポーネントによる再レンダリングが行われる可能性がないため、直接アロー関数を記載しても特に問題はないということでしょうか？👀

直接関数を渡すと、ソース読み込みのタイミングで即時関数が実行されてしまうため、theme選択の挙動に問題が発生する懸念があるという意味であっていますか？🤔

2024-05-31 00:53 UTC, NBmaeda commented on src/Components/ThemeChange.tsx
> +						<button className={`theme1-num ${selectedTheme === 1 ? 'active' : ''}`} onClick={handleThemeChange(1)}>1</button>
@NByamane 
返事遅くなってすみません🙏

> こちらなのですが、onClick={() => handleThemeChange(1)}といった書き方をするという意味でしょうか？🤔

自分のコメントで「前述のhandleThemeChangeのとこのコメントでも~」 とか書いてしまっていますが、「後述の」ですねすみません😇
`ThemeChange.tsx`のコメントに書いてある`handleClickThemeBtn`を参考にしてみてください。

このアプリでも`state`変更の際に親コンポーネントの再レンダリングが行われている形にはなります。ただパフォーマンスをめちゃくちゃ最適化するわけではないのであれば、「直接アロー関数を渡す」でもいいと思っています。
ですがこの場合は、DOMに持たせた値を使うとアロー関数も使わなくて良いしシンプルなので、個人的にはそれが良いかなという判断です💡

> 直接関数を渡すと、ソース読み込みのタイミングで即時関数が実行されてしまうため、theme選択の挙動に問題が発生する懸念があるという意味であっていますか？🤔

今回に限ると「theme選択の挙動に問題が発生」というよりかは、もしかするとページ読み込みの際にtheme切り替えが発生するので、チラつきや想定外の見た目の切り替わりなどが発生するかもな、という感じです。
他の場合でもハンドラとして登録した関数がページ読み込み時に実行されると好ましくない場合があるので、それを覚えておいて欲しいです💡

2024-05-31 07:42 UTC, NByamane commented
@NBmaeda 
お疲れ様です🙇‍♀️
1点質問させてください🙋‍♀️

現状まだtoLocaleString()を使った、1000の位ごとにカンマで区切る実装は行なっていません👀
updateCurrentの部分で使用しようと思ったのですが、以下のコードで上手く挙動しません😫

```
function updateCurrent(newCurrent: string, state: State, isNextClear = false): State {
	const formattedNewCurrent = parseFloat(newCurrent).toLocaleString();
	return {
		...state,
		current: formattedNewCurrent,
		isNextClear,
	};
}
```

このコードだと、1000の位に達した後に数値buttonを押すと、また1の位からの入力になり、1000以上の入力ができなくなってしまいました🤔
これは私がこの条件の場合、isNextClearをtrueにする実装にしてるのかとは思うのですが、数値button周りの挙動でそのような挙動にした記憶もコードも見当たらず、困っています😇
今原因を探っているのですが、この実装方針がまずい場合はアドバイスいただけますと幸いです🥲

その他レビューも含め、よろしくお願い致します🙇‍♀️🙏🙇‍♀️

2024-05-31 08:47 UTC, NBmaeda commented
@NByamane 

> @NBmaeda お疲れ様です🙇‍♀️ 1点質問させてください🙋‍♀️
> 
> このコードだと、1000の位に達した後に数値buttonを押すと、また1の位からの入力になり、1000以上の入力ができなくなってしまいました🤔 これは私がこの条件の場合、isNextClearをtrueにする実装にしてるのかとは思うのですが、数値button周りの挙動でそのような挙動にした記憶もコードも見当たらず、困っています😇 今原因を探っているのですが、この実装方針がまずい場合はアドバイスいただけますと幸いです🥲

まだコードの変更追えてないのでなんともですが、`calsulate.ts`の`clickNumButton`の中で、`updateCurrent`が呼ばれる前に`state.current`の末尾にクリックした数値付け加えてると思います。
その際に「1,000」→「1,0000」みたいな、本来存在しないコンマ区切りの数値になってる可能性ないでしょうか？

`updateCurrent`の中で`toLocaleString()`して`state`に保存するではなく、あくまで`state`ではコンマなしの状態で持っておいて、表示箇所でだけコンマつけるのはどうですか？🤔

2024-05-31 08:58 UTC, NByamane commented
@NBmaeda 
ありがとうございます🙇‍♀️
確かにでした、とてもシンプルに実装できました😅✨
追加でカンマ区切りも実装に含め、コミットしました🙇‍♀️
併せてご確認のほど、よろしくお願い致します🍬

2024-06-03 03:46 UTC, NBmaeda approved these changes
対応お疲れ様でした！
当初予定していた機能は実装できたと思いますし、内部のコードやパフォーマンスの改善も実施できたと思います👏
Approveしました、第1弾は完成で良いと思います🎉

+αでやると良いことを今回のコメントに記載しておきましたので、目を通した上で実装して、動きを確認してもらえると幸いです。

今回の課題では以下のようなことを学ぶことができたのではないかと思います。
oneshiさん自身でも、各課題や記事執筆を通じてどういったことを学んだか、さらに発展して何を学ぶべきか、といったことをまとめておくと質の良い学びにつながると思います💡
```
# パフォーマンスのためのReactの工夫
- 再レンダリングを防ぐための、コンポーネント分割
- 再レンダリングを防ぐための、`React.memo()`の使用

# コード面
- Dry原則の利用
- 関数名の最適化
- 使用する関数の統一
- 管理する状態の設計
- スプレッド構文の活用
```

2024-06-03 03:46 UTC, NBmaeda commented on src/Components/Display.tsx
> +			<p className="calculator-result">{ formattedValue }</p>
良いですね！
先日のコメントでも伝えましたが、裏側で持っておく状態などは加工しやすい状態で保存しておいて、情報を見せる際に適切な形に加工するという前提で考えると良いと思います💡

2024-06-03 03:46 UTC, NBmaeda commented on src/Components/ThemeChange.tsx
> +			setSelectedTheme(Number(event.target.value));
`Display.tsx`では、文字列→数値の変換に`parseFloat()`を使用していると思います。
`Number()`とどちらでもいいのですが、統一していた方がコード全体の可読性は上がると思います。

2024-06-03 03:46 UTC, NBmaeda commented on src/App.tsx
> +      <ThemeChange onThemeChange={handleThemeChange} />
良いですね。
こうやって`ThemaChange`を分けたことで、計算機を使用した際に`ThemaChange`の再レンダリングが実行されないようになりました。
React Developer Toolsで確認できると思います。

2024-06-03 03:46 UTC, NBmaeda commented on src/Components/Calculator.tsx
> +export const Calculator = (): JSX.Element => {
この`Calculator`コンポーネント自体を、`React.memo()`で囲むことで、themaChangeを実行した際の`Calculator`の再レンダリングを防止してくれます。
親コンポーネントでstateの更新を行った場合は子コンポーネントも再レンダリングされてしまうので、こういった工夫で改善できることを頭に入れておくと良いです。

2024-06-10 08:39 UTC, NByamane commented
@NBmaeda 
お疲れ様です🙇‍♀️
レビューありがとうございました🎉
いただいた点を修正してpushしました🙏
こちらでマージします🫡

また、アドバイスいただいた以下も対応しようと思います🥰

>各課題や記事執筆を通じてどういったことを学んだか、さらに発展して何を学ぶべきか、といったことをまとめておくと質の良い学びにつながると思います💡

2024-06-10 08:39 UTC, merged